name: peerdart_exp
version: 2.0.0
homepage: https://github.com/MuhammedKpln/peerdart
description: Simple peer-to-peer with WebRTC for Dart. PeerJS port for Flutter.
repository: https://github.com/shukill/peerdart_exp
environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.22.0"
dependencies:
  http: ^1.1.0
  uuid: ^4.5.1
  flutter_webrtc: ^0.12.11
  web_socket_channel: ^3.0.2
  events_emitter: ^0.6.0
  sdp_transform: ^0.3.2
dev_dependencies:
  lints: ^2.0.0
  flutter_test:
    sdk: flutter
